# Define the goal
uint32 dishwasher_id  # Specify which dishwasher we want to use
geometry_msgs/Pose pose
geometry_msgs/Twist twist
---
# Define the result
geometry_msgs/Pose finish_pose
---
# Define a feedback message
geometry_msgs/Pose current_pose
